name: SSH deploy on push
on:
  push:
    branches:
      - main # Убедитесь, что ваша ветка в GitHub называется именно main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: rsync deploy
        # ИСПРАВЛЕНО: @main вместо @8
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}
